### ISSUE TITLE
Port elle to tipocket as a checker

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tipocket#153]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Port [elle](https://github.com/jepsen-io/elle/tree/master/src/elle) to tipocket. 

**Describe the feature you'd like:**

None

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by mahjonp** [comment]
close by https://github.com/pingcap/tipocket/pull/225
