### ISSUE TITLE
Make test-infra/recommendation become an interface

### ISSUE THREAD

**Issue by yeya24** [pingcap/tipocket#154]
The test-infra code contains several ways to start a cluster: TidbCluster, ABTest, CDC, Binlog... However, it is quite hard to reuse these components. Like if I want to have CDC and Tiflash at the same time, the only way to achieve it is to add another recommendation for this case. 

It is better to make recommendation as an interface with several common methods, like:
1. Apply
2. Delete
3. GetClientNodes(?)
4. GetNodes

**Comment by mahjonp** [comment]
It's very useful, especially when the deployment topology we need support become more.
