### ISSUE TITLE
port tikv_rawkv_randgen_and_checker

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tipocket#181]
## Feature Request

https://gist.github.com/MyonKeminta/6a9d60111bbe2f6f96b091ac474d2fc4 can detect cf errors
we can port it to tipocket

It has already test an issue in https://github.com/tikv/tikv/issues/6519

**Comment by yeya24** [comment]
Does `tipocket` support testing on raw `tikv` directly?
