### ISSUE TITLE
Make CF consistency

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tipocket#19]
## Feature Request

**Is your feature request related to a problem? Please describe:**

CF consistency should be ensure

**Describe the feature you'd like:**

CF consistency should be ensure

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by siddontang** [comment]
can you describe in more detail so others can help us add this test?

**Comment by zhouqiang-cl** [comment]
> can you describe in more detail so others can help us add this test?

OK. I will add the TODO list here
