### ISSUE TITLE
add an option to disable tidb monitor

### ISSUE THREAD

**Issue by yeya24** [pingcap/tipocket#197]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

It would be nice to have an option to disable tidb monitor. Sometimes we don't really need a Prometheus and Grafana.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mahjonp** [comment]
You mean the problem that chaos-mesh dashboard creates a Grafana if it finds a tidb monitor exists?

**Comment by yeya24** [comment]
No. I just think in some when you do some case local testing or development, tidb monitor is not actually required.
