### ISSUE TITLE
Add guide for tipocket

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tipocket#21]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now tipocket is just a very simple readme, it did not guide how to use the cases, and how to develop more features. We should add the guide

**Describe the feature you'd like:**

- Add overview guide
- Add develop guide
- Add user guide

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by mahjonp** [comment]
Closed by https://github.com/pingcap/tipocket/pull/247
