### ISSUE TITLE
Add a document for nemesis

### ISSUE THREAD

**Issue by yeya24** [pingcap/tipocket#223]
## Feature Request

Tipocket doesn't have a doc for nemesis now and it is hard for users to choose nemesis to their test cases.

We should have a doc to introduce/explain the different kinds of nemesis.

**Comment by mahjonp** [comment]
Good suggestion, we can do it on this special week.

**Comment by mahjonp** [comment]
Closed by https://github.com/pingcap/tipocket/pull/247
