### ISSUE TITLE
Use chaos-mesh to impl Nemesis

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tipocket#24]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

[chaos-mesh](https://github.com/pingcap/chaos-mesh) is a cloud-native Chaos Engineering platform that orchestrates chaos on Kubernetes environments, we could use it to injection pod-kill/pod-failure/netem chaos/network-partition/IO chaos etc faults.

There exists a [proposal](https://github.com/pingcap/chaos-mesh/issues/72) on chaos-mesh that support some kinds of fault to last a long duration until the user stop them, that's what we need to use in our workloads to injection manageable faults.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mahjonp** [comment]
PTAL @mapleFU

**Comment by mapleFU** [comment]
Seems that `nemesis` means a client to inject fault to k8s cluster. What about the style we're using it?

**Comment by mahjonp** [comment]
> Seems that `nemesis` means a client to inject fault to k8s cluster. What about the style we're using it?

You can refer the code on test-infra directory, and reorganize them inside pkg
