### ISSUE TITLE
Support simulating data center disaster

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tipocket#261]
## Feature Request

**Describe the feature you'd like:**
We usually use label to distinguish different data center. To simulating data center disaster, it can provide an API to make all nodes that have the same label crash. To test features like asynchronous replication, it's also required to make those nodes keep offline.

A simple alternative is constructing a network partition between data center.

**Comment by mahjonp** [comment]
#262 and #264 support an approach to control nemeses on the test client-side and have provided a new NemesisGeneator named NewCoordinationKillGenerator, you can use it to kill specified nodes when checking.

Here gives a demo shows how to control nemesis in test client:

```go
func (c *Case) Start(ctx context.Context, cfg interface{}, clientNodes []types.ClientNode) error {
	control := ctx.Value("control").(*control.Controller)

	for i := 1; i <= 3; i++ {
		killGenerator, nemesisControl := nemesis.NewCoordinationKillGenerator(c.nodes[0:i])
		control.UpdateNemesisGenerators(core.NewOneRoundNemesisGenerators(killGenerator))
		// Start blocks until nemesis is prepared to start
		nemesisControl.Start(ctx)

		log.Info("nemesis starts")
		time.Sleep(5 * time.Minute)
		log.Info("5 minutes later...")

		// recover nemesis, but won't block.
		nemesisControl.Rollback(ctx)
                ...
	}
        ...
}
```

**Comment by BusyJay** [comment]
Thanks!
