### ISSUE TITLE
no bank.yaml  in argo directory

### ISSUE THREAD

**Issue by danche** [pingcap/tipocket#290]
## Bug Report

**What did you do?**
![image](https://user-images.githubusercontent.com/4171668/86530146-ddbc0b80-bee8-11ea-853e-f5368d9e54c4.png)

**What did you expect to see?**

**What did you see instead?**

**Comment by danche** [comment]
![image](https://user-images.githubusercontent.com/4171668/86530153-edd3eb00-bee8-11ea-9e95-dd8ccdae3083.png)

**Comment by danche** [comment]
https://github.com/pingcap/tipocket/tree/master/argo#submit-a-new-workflow

**Comment by zhouqiang-cl** [comment]
@mahjonp PTAL

**Comment by mahjonp** [comment]
@danche Thanks, we have fixed it. :)
