### ISSUE TITLE
支持在命令行参数中指定集群配置

### ISSUE THREAD

**Issue by cosven** [pingcap/tipocket#324]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tipocket/issues/321

**Describe the feature you'd like:**

当前，用例可以指定集群的 `配置文件`，这个配置文件需要预定义好，放在 `config/` 目录下。
在构建 tipocket 的镜像的时候，这些预定义的配置文件会被加入到 docker 镜像中。

我们会这样运行用例
```sh
bin/testcase -tikv-config 'config/tikv/xxx.toml' -option-x -option-y -option-z
```

但预定义的配置文件太死板了，希望能够在用例的命令行参数中传入集群配置

**Solution**

举个例子
```sh
bin/testcase -tikv-config "log-level = info" -option-x -option-y -option-z
```

考虑到配置中可能包含特殊字符，我们可以使用 base64 对配置先进行编码。
我们可以如下

```sh
bin/testcase -tikv-config "b64encoded-config" -option-x -option-y -option-z
```

**Note**

1. 需要考虑向后兼容

**Comment by cosven** [comment]
cc @mahjonp

**Comment by ofey404** [comment]
我也遇到了这个需求……

每次应用一个新的配置文件，现在都要编译一个新的镜像，这样不太好。

**Comment by ofey404** [comment]
直接在原来的-tikv-config这个flag上面改，会不会增加要和原本兼容的代码复杂度，和额外的命令学习成本？

增加一个flag也是一种可行的方案，可以不用和原来的-tikv-config逻辑耦合，不知大家觉得如何。

```bash
bin/testcase -tikv-config-instant "b64encoded-config" -option-x -option-y -option-z
```

**Comment by cosven** [comment]
DONE https://github.com/pingcap/tipocket/pull/330
