### ISSUE TITLE
TiPocket 部署 TiDB 集群时，grafana 面板使用尽可能新的版本

### ISSUE THREAD

**Issue by cosven** [pingcap/tipocket#333]
**当前**

TiPocket 部署的 TiDB 集群的监控 grafana 面板比较老旧，缺少很多面板，这降低大家排查问题的效率。
举个例子：TiKV fast tune 面板就没有。

TiKV 对 grafana 面板的配置：https://github.com/tikv/tikv/tree/master/metrics

![image](https://user-images.githubusercontent.com/4962134/102451592-b9598300-4073-11eb-9a5d-cb14ceb2be9d.png)

**期望**

尽可能显示最新的监控面板。

比如 tiup 可以显示更完整的面板
![image](https://user-images.githubusercontent.com/4962134/102452163-db073a00-4074-11eb-85ca-ababf0506597.png)

**Comment by cosven** [comment]
https://github.com/pingcap/monitoring/pull/85
从这个 PR 可以看出，tidb operator 使用的 grafana dashboard 配置确实比较老旧。
要解决这个问题，需要从 tidb-monitor-initializer 这个镜像的打包发布上手。

**Comment by mahjonp** [comment]
Now tipocket uses the pingcap/tidb-monitor-initializer:nightly image, close this issue.
