### ISSUE TITLE
Export tikv status server port

### ISSUE THREAD

**Issue by NingLin-P** [pingcap/tipocket#351]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, tipocket did not export TiKV's status server port, which provides API likes `/debug/pprof/heap` and `/debug/pprof/profile`, they can be very helpful when debugging test.

**Describe the feature you'd like:**

Export TiKV's status server port like TiKV's grpc server port

**Describe alternatives you've considered:**

**Comment by mahjonp** [comment]
Yep, but in this case, IMO kubectl port-foward combined with tidb-dashboard are more direct. Support your namespace is sr:

```
kubectl port-forward --address 0.0.0.0  pod/sr-tikv-1 -n sr 23790:2379
open http://127.0.0.1:23790/dashboard/#/signin
```
