### ISSUE TITLE
Why keep adding new flags in fixture?

### ISSUE THREAD

**Issue by xhebox** [pingcap/tipocket#361]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

All default configs/flags of tidb/cdc/... are  in the fixture package. And I always have very, very long list of cmd flags even if I am not using cdc or whatever.

I noticed that #162 refactored methods `RecommendedCluster`, and move them from their own packages into `test_infra`. Actually, why not move different variables in the fixture package back to different packages?

For example, `tidb.NewCluster(opts...Options)` in the tidb package, `ticdc.NewCluster(WithImage(...))` in the ticdc package? You can include the most common flags in the suit package.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mahjonp** [comment]
I have noticed that, the refactor plan on fixture.go is on my schedule.
