### ISSUE TITLE
Migrate Schrodinger/check/admin_check

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tipocket#60]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Refs: https://github.com/pingcap/schrodinger-test/tree/master/check/admin_check

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cwen0** [comment]
@mahjonp Got, I will work on it.
